services:
  postgres:
    image: postgres:14.7
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    profiles: ['all', 'dev']
